name: SlamPackage
main: com.slamtheham.slampackage.Main
description: SlamPackage is a Custom Enchants plugin with many features.
version: Indev-v8.21.2018-0.01
author: Developed by SlamTheHam

commands:
  enchanter:
    usage: /<command>
    description: Open the enchanter menu.
  slampackage:
    usage: /<command>
    description: The plugins core command.  